name: Deploy to Railway DEV Environtment

on:
  push:
    branches:
      - "develop"


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NodeJs '20.x'
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'

      - name: Install Package
        run: npm install
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}