name: Deploy to Railway PROD Environtment

on:
  push:
    branches:
      - "main"


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJs '18.x'
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Package
        run: npm install
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROD_TOKEN }}
